# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Lint Check
        run: npm run lint

      # - name: Build Wechat App
      #   run: npm run build

      # 从 secrets.UPLOAD_PRIVATE_KEY 生成私钥文件
      # see Project/Settings/Secrets
      # - name: Generate private key for upload
      #   run: echo "$UPLOAD_PRIVATE_KEY" > private.key
      #   env:
      #     UPLOAD_PRIVATE_KEY: ${{ secrets.UPLOAD_PRIVATE_KEY }}
      
      # 上传代码
      - name: Login to tcb
        run: npx tcb login --apiKeyId $TCB_API_KEY_ID --apiKey $TCB_API_KEY
        env:
          TCB_API_KEY_ID: ${{ secrets.TCB_API_KEY_ID }} 
          TCB_API_KEY: ${{ secrets.TCB_API_KEY }}

      # - name: Export Schemas
      #   run: npm run build-schema
      #   env:
      #     TCB_API_KEY_ID: ${{ secrets.TCB_API_KEY_ID }} 
      #     TCB_API_KEY: ${{ secrets.TCB_API_KEY }}
      #     WX_APPID: ${{ secrets.WX_APPID }}
      #     UPLOAD_PRIVATE_KEY: ${{ secrets.UPLOAD_PRIVATE_KEY }}
      #     ENV_ID: ${{ secrets.ENV_ID }} 

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      # - name: DEBUG
      #   run: |
      #     echo $GITHUB_SHA
      #     echo $GITHUB_REF
      #     echo $(git rev-parse --short "$GITHUB_SHA")
      #     echo ${GITHUB_REF#refs/heads/}
      #     echo ${{ steps.vars.outputs.sha_short }} 
      #     echo ${{ steps.vars.outputs.branch }}

      - name: Deploy
        run: npm run deploy --verbose
        env:
          TCB_API_KEY_ID: ${{ secrets.TCB_API_KEY_ID }} 
          TCB_API_KEY: ${{ secrets.TCB_API_KEY }}
          WX_APPID: ${{ secrets.WX_APPID }}
          UPLOAD_PRIVATE_KEY: ${{ secrets.UPLOAD_PRIVATE_KEY }}
          ENV_ID: ${{ secrets.ENV_ID }}
          CMS_API_TOKEN: ${{ secrets.CMS_API_TOKEN }}
          CMS_BASE_URL: ${{ secrets.CMS_BASE_URL }}
          COMMIT_SHA: ${{ steps.vars.outputs.sha_short }}
          BRANCH: ${{ steps.vars.outputs.branch }}
    
      # - name: Upload Artifacts 🚀
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: schema
      #     path: output/schemas.json
